### ISSUE TITLE
Could not find property 'android' on project ':domain'

### ISSUE THREAD

**Issue by delor** [pjakubczyk/robospock-plugin#11]
I was trying to add java-only module to android application but this happens:

```
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\delor\AndroidStudioProjects\Finance\app-test\build.gradle' line: 12

* What went wrong:
A problem occurred evaluating project ':app-test'.
> Could not find property 'android' on project ':domain'.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':app-test'.
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:54)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:156)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:38)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:25)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:507)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:82)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:31)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:142)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:113)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:81)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:64)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:50)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:201)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:174)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:170)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:139)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:46)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.Main.main(Main.java:37)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:50)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:32)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
Caused by: groovy.lang.MissingPropertyException: Could not find property 'android' on project ':domain'.
        at org.gradle.api.internal.AbstractDynamicObject.propertyMissingException(AbstractDynamicObject.java:43)
        at org.gradle.api.internal.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:35)
        at org.gradle.api.internal.CompositeDynamicObject.getProperty(CompositeDynamicObject.java:94)
        at org.gradle.api.internal.project.DefaultProject_Decorated.getProperty(Unknown Source)
        at org.robospock.RobospockAction$_execute_closure2.doCall(RobospockAction.groovy:40)
        at org.robospock.RobospockAction.execute(RobospockAction.groovy:35)
        at org.robospock.RobospockAction$execute.call(Unknown Source)
        at org.robospock.RobospockPlugin.apply(RobospockPlugin.groovy:9)
        at org.robospock.RobospockPlugin.apply(RobospockPlugin.groovy)
        at org.gradle.api.internal.plugins.DefaultPluginContainer.providePlugin(DefaultPluginContainer.java:104)
        at org.gradle.api.internal.plugins.DefaultPluginContainer.addPluginInternal(DefaultPluginContainer.java:68)
        at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultPluginContainer.java:34)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyPlugin(DefaultObjectConfigurationAction.java:101)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:32)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:72)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:114)
        at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:39)
        at org.gradle.api.Project$apply.call(Unknown Source)
        at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.groovy:34)
        at org.gradle.api.Script$apply.callCurrent(Unknown Source)
        at build_7trcsdq1outdso1ps56pn8knh3.run(C:\Users\delor\AndroidStudioProjects\Finance\app-test\build.gradle:12)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)
        ... 33 more
```

``` groovy
// file: domain/build.gradle

apply plugin: 'java'
apply plugin: 'groovy'

dependencies {
  groovy('org.codehaus.groovy:groovy-all:2.0.5')
  compile 'org.spockframework:spock-core:0.7-groovy-2.0'

  testCompile "org.hamcrest:hamcrest-core:1.2"
  testRuntime "cglib:cglib-nodep:2.2"
  testRuntime "org.objenesis:objenesis:1.2"
}
```

``` groovy
// file: app/build.gradle

apply plugin: 'android'

android {
  compileSdkVersion 19
  buildToolsVersion "19.0.3"

  defaultConfig {
    minSdkVersion 8
    targetSdkVersion 19
    versionCode 1
    versionName "1.0"
  }
  buildTypes {
    release {
      runProguard false
      proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
    }
  }
}

dependencies {
  compile project(':domain')
  compile fileTree(dir: 'libs', include: ['*.jar'])
  compile 'com.android.support:appcompat-v7:19.+'
}
```

``` groovy
// file: app-test/build.gradle

apply plugin: 'groovy'

dependencies {
  compile "org.codehaus.groovy:groovy-all:1.8.6"
  compile 'org.robospock:robospock:0.4'
}

project.ext {
  robospock = ":app"
}

apply plugin: 'robospock'
```

**Comment by georgepapas** [comment]
in your app-test project, you need to add the line 

```
evaluationDependsOn(':app')
```

This will ensure gradle loads your app first, thereby loading the anroid plugin and making it available to the spock plugin

**Comment by delor** [comment]
Changing it to following didn't change anything.

``` groovy
apply plugin: 'groovy'

dependencies {
  compile "org.codehaus.groovy:groovy-all:1.8.6"
  compile 'org.robospock:robospock:0.4'
}

project.ext {
  robospock = ":app"
}

evaluationDependsOn(':app')

apply plugin: 'robospock'
```

**Comment by georgepapas** [comment]
Hi,

Please see the README of project.  

The evaluationDependsOn needs to be at the top of your gradle build file.

**Comment by delor** [comment]
I have tried that, it didn't help.

**Comment by pjakubczyk** [comment]
Did you check what happens without "apply plugin: 'groovy'" in domain/build.gradle - Android might have problems with groovy

**Comment by ened** [comment]
Does the 'evaluationDependsOn' trick still works for you with the latest Android Gradle plugin (0.14)?

**Comment by jenzz** [comment]
`evaluationDependsOn(':app')` right after `apply plugin: 'java'` works for me (plugin v0.14.1).

Tnx! :smile:
